const express = require('express');
const driver = require('../db');
const router = express.Router();
const neo4j = require('neo4j-driver');

// Helper function to generate unique IDs with domain prefix
const generateId = (domain, count) => {
  const prefix = domain.substring(0, 3).toUpperCase();
  const timestamp = Date.now().toString().substring(7);
  return `${prefix}-${timestamp}-${count.toString().padStart(3, '0')}`;
};

// AI templates for different domains
const domainTemplates = {
  Mission: [
    {
      title: "Orbital Debris Mitigation",
      description: "Develop technologies and strategies to identify, track, and remove orbital debris threatening operational satellites and space infrastructure.",
      childMissionIds: []
    },
    {
      title: "Autonomous Space Operations",
      description: "Enable spacecraft to perform orbital maneuvers, docking, and various mission operations with minimal human intervention.",
      childMissionIds: []
    },
    {
      title: "Deep Space Propulsion Development",
      description: "Research and develop advanced propulsion technologies for faster interplanetary transit and extended mission capabilities.",
      childMissionIds: []
    },
    {
      title: "Sustainable Lunar Presence",
      description: "Establish continuous human presence on the lunar surface with sustainable resource utilization and habitat development.",
      childMissionIds: []
    },
    {
      title: "Mars Sample Return",
      description: "Develop and execute missions to collect and return samples from the Martian surface for detailed analysis on Earth.",
      childMissionIds: []
    }
  ],
  Scenario: [
    {
      title: "Rendezvous with Debris Object",
      description: "Spacecraft approaches and matches velocity with targeted debris object prior to capture operations.",
      childScenarioIds: []
    },
    {
      title: "Solar Panel Deployment Failure Recovery",
      description: "Response scenario for incomplete deployment of primary power generation systems during critical mission phase.",
      childScenarioIds: []
    },
    {
      title: "Radiation Shielding Performance Test",
      description: "Validation of radiation protection systems during solar flare events to ensure crew safety.",
      childScenarioIds: []
    },
    {
      title: "Autonomous Docking Procedure",
      description: "Computer-controlled approach and docking with International Space Station without ground control intervention.",
      childScenarioIds: []
    },
    {
      title: "Mars Landing Site Selection",
      description: "Real-time terrain analysis and landing site selection during descent phase to avoid hazards.",
      childScenarioIds: []
    }
  ],
  Requirements: [
    {
      title: "Debris Capture System Range",
      description: "The debris capture system shall be capable of securing objects between 10cm and 2m in diameter.",
      childRequirementIds: []
    },
    {
      title: "Autonomous Navigation Precision",
      description: "The spacecraft shall maintain relative position accuracy of ±0.5m during autonomous operations at distances up to 1000km from Earth.",
      childRequirementIds: []
    },
    {
      title: "Radiation Hardening Standard",
      description: "All critical electronic systems shall function nominally during and after exposure to radiation doses up to 100 krad(Si).",
      childRequirementIds: []
    },
    {
      title: "Life Support Duration",
      description: "The life support system shall maintain survivable atmosphere, water, and temperature for crew of 4 for minimum of 30 days without resupply.",
      childRequirementIds: []
    },
    {
      title: "Communication Latency Tolerance",
      description: "Mission-critical systems shall function autonomously during communication latencies up to 40 minutes round-trip.",
      childRequirementIds: []
    }
  ],
  Parameter: [
    {
      title: "Maximum Debris Mass",
      description: "The maximum mass of debris object that can be captured by the system.",
      unit: "kg",
      valueType: "number",
      childParameterIds: []
    },
    {
      title: "Propellant Reserve Margin",
      description: "Minimum propellant reserve that must be maintained for emergency maneuvers.",
      unit: "%",
      valueType: "number",
      childParameterIds: []
    },
    {
      title: "Solar Array Power Generation",
      description: "Total electrical power generated by solar arrays at 1 AU from Sun.",
      unit: "kW",
      valueType: "number",
      childParameterIds: []
    },
    {
      title: "Thermal Operating Range",
      description: "Temperature range within which all systems remain fully operational.",
      unit: "°C",
      valueType: "range",
      childParameterIds: []
    },
    {
      title: "Communication Bandwidth",
      description: "Maximum data transmission rate between spacecraft and ground stations.",
      unit: "Mbps",
      valueType: "number",
      childParameterIds: []
    }
  ],
  Functions: [
    {
      title: "Trajectory Optimization",
      description: "Calculates optimal spacecraft trajectory to minimize propellant consumption while meeting mission timeline constraints.",
      functionType: "calculation",
      childFunctionIds: []
    },
    {
      title: "Thermal Load Balancing",
      description: "Distributes thermal loads across spacecraft systems to maintain operational temperature ranges.",
      functionType: "control",
      childFunctionIds: []
    },
    {
      title: "Power Management",
      description: "Allocates available power to subsystems based on mission phase priorities and constraints.",
      functionType: "control",
      childFunctionIds: []
    },
    {
      title: "Object Recognition",
      description: "Identifies and classifies objects in sensor data using machine learning algorithms.",
      functionType: "data processing",
      childFunctionIds: []
    },
    {
      title: "Fault Detection Isolation and Recovery",
      description: "Identifies system anomalies, isolates faulty components, and implements recovery procedures.",
      functionType: "safety",
      childFunctionIds: []
    }
  ]
};

// Program-specific templates for different program types
const programSpecificTemplates = {
  "Missile System": {
    Mission: [
      {
        title: "Precision Strike Capability",
        description: "Develop missile systems capable of neutralizing high-value targets with minimal collateral damage across various operational environments.",
        childMissionIds: []
      },
      {
        title: "Extended Range Deployment",
        description: "Increase missile effective range while maintaining accuracy and reliability metrics across diverse weather conditions.",
        childMissionIds: []
      },
      {
        title: "Counter-Measure Resilience",
        description: "Enhance missile systems to maintain effectiveness against advanced electronic countermeasures and defensive interceptors.",
        childMissionIds: []
      },
      {
        title: "Rapid Response Deployment",
        description: "Minimize time-to-target through improved propulsion systems and streamlined launch procedures.",
        childMissionIds: []
      },
      {
        title: "Multi-Domain Integration",
        description: "Ensure seamless missile system coordination with air, ground, and naval forces through integrated command and control systems.",
        childMissionIds: []
      }
    ],
    Scenario: [
      {
        title: "Urban Environment Engagement",
        description: "Missile operation in densely populated areas with strict collateral damage limitations and complex targeting requirements.",
        childScenarioIds: []
      },
      {
        title: "Naval Defense Penetration",
        description: "Approach and target acquisition against naval vessels with active defense systems in adverse weather conditions.",
        childScenarioIds: []
      },
      {
        title: "Multi-Missile Coordinated Strike",
        description: "Synchronized attack using multiple missiles against interconnected defense infrastructure.",
        childScenarioIds: []
      },
      {
        title: "Electronic Warfare Environment",
        description: "Operation in heavily contested electromagnetic spectrum with active jamming and spoofing countermeasures.",
        childScenarioIds: []
      },
      {
        title: "Extended Range Border Defense",
        description: "Long-duration flight to engage threats approaching national borders before they reach sovereign airspace.",
        childScenarioIds: []
      }
    ],
    Requirements: [
      {
        title: "Circular Error Probable",
        description: "The missile system shall achieve a CEP of less than 3 meters at maximum operational range.",
        childRequirementIds: []
      },
      {
        title: "Launch Platform Compatibility",
        description: "The missile system shall be deployable from air, ground, and naval platforms without modification to core missile components.",
        childRequirementIds: []
      },
      {
        title: "Electronic Countermeasure Resistance",
        description: "The guidance system shall maintain target lock during exposure to jamming signals of up to 500W effective radiated power.",
        childRequirementIds: []
      },
      {
        title: "Operational Temperature Range",
        description: "The missile system shall perform to specification in ambient temperatures from -40°C to +60°C.",
        childRequirementIds: []
      },
      {
        title: "Shelf Life Duration",
        description: "The missile system shall maintain operational readiness when stored in approved conditions for up to 15 years without maintenance.",
        childRequirementIds: []
      }
    ],
    Parameter: [
      {
        title: "Maximum Operational Range",
        description: "The maximum distance from which the missile can be launched and still effectively reach its target.",
        unit: "km",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Warhead Explosive Yield",
        description: "Total explosive energy delivered by the missile's warhead upon detonation.",
        unit: "kg TNT equivalent",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Maximum Flight Speed",
        description: "Peak velocity attainable by the missile during its flight trajectory.",
        unit: "Mach",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Guidance System Accuracy",
        description: "Precision of the guidance system in ideal conditions.",
        unit: "meters CEP",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Target Acquisition Time",
        description: "Time required for the missile to lock onto a designated target after launch.",
        unit: "seconds",
        valueType: "number",
        childParameterIds: []
      }
    ],
    Functions: [
      {
        title: "Terminal Guidance Calculation",
        description: "Processes sensor data to make final trajectory adjustments during terminal approach to target.",
        functionType: "calculation",
        childFunctionIds: []
      },
      {
        title: "Countermeasure Detection and Classification",
        description: "Identifies electronic countermeasures and determines appropriate response strategies.",
        functionType: "data processing",
        childFunctionIds: []
      },
      {
        title: "Propulsion Stage Management",
        description: "Controls the sequencing and performance of multiple propulsion stages for optimal flight profile.",
        functionType: "control",
        childFunctionIds: []
      },
      {
        title: "Target Priority Assessment",
        description: "Evaluates multiple potential targets and selects highest priority based on mission parameters.",
        functionType: "decision",
        childFunctionIds: []
      },
      {
        title: "Terrain Contour Matching",
        description: "Compares real-time sensor data with stored terrain maps for precision navigation in GPS-denied environments.",
        functionType: "navigation",
        childFunctionIds: []
      }
    ]
  },
  "Commercial Aircraft": {
    Mission: [
      {
        title: "Regional Transportation Network",
        description: "Develop aircraft optimized for high-frequency, short to medium range routes connecting regional business centers.",
        childMissionIds: []
      },
      {
        title: "Intercontinental Passenger Service",
        description: "Provide efficient, comfortable long-haul transportation between major international destinations.",
        childMissionIds: []
      },
      {
        title: "Cargo Transport Optimization",
        description: "Maximize cargo capacity and loading efficiency while ensuring economic operation on standard shipping routes.",
        childMissionIds: []
      },
      {
        title: "Fuel Efficiency Enhancement",
        description: "Reduce fuel consumption per passenger-mile through advanced aerodynamics and propulsion technologies.",
        childMissionIds: []
      },
      {
        title: "Operational Noise Reduction",
        description: "Minimize aircraft noise footprint during all phases of flight to enable operations at noise-sensitive airports.",
        childMissionIds: []
      }
    ],
    Scenario: [
      {
        title: "High Altitude Cruise Efficiency",
        description: "Optimization of aircraft performance during extended cruise at FL350-FL410 in varying atmospheric conditions.",
        childScenarioIds: []
      },
      {
        title: "Crosswind Landing Operation",
        description: "Aircraft approach and landing procedures during strong crosswind conditions at challenging airports.",
        childScenarioIds: []
      },
      {
        title: "Rapid Turnaround Procedure",
        description: "Ground operations optimized for minimum time between arrival and subsequent departure.",
        childScenarioIds: []
      },
      {
        title: "Extended ETOPS Operation",
        description: "Long-distance flight routes over oceanic regions with limited diversion airports available.",
        childScenarioIds: []
      },
      {
        title: "High-Density Airport Integration",
        description: "Operation at congested hub airports with minimal separation and precise schedule adherence requirements.",
        childScenarioIds: []
      }
    ]
  },
  "Fighter Aircraft": {
    Mission: [
      {
        title: "Air Superiority Campaign",
        description: "Establish and maintain control of contested airspace through detection, engagement and neutralization of enemy air assets.",
        childMissionIds: []
      },
      {
        title: "Precision Strike Capability",
        description: "Deliver guided munitions against high-value ground targets with minimal collateral damage.",
        childMissionIds: []
      },
      {
        title: "Electronic Warfare Operations",
        description: "Disrupt enemy radar, communications and targeting systems through advanced electronic countermeasures.",
        childMissionIds: []
      },
      {
        title: "Reconnaissance and Surveillance",
        description: "Collect high-resolution intelligence on enemy positions and movements across various sensor spectrums.",
        childMissionIds: []
      },
      {
        title: "Air Defense Suppression",
        description: "Locate, target and neutralize enemy air defense systems to create safe corridors for friendly aircraft.",
        childMissionIds: []
      }
    ],
    Parameter: [
      {
        title: "Maximum Combat Radius",
        description: "Maximum distance the aircraft can travel from base, perform combat operations, and return with reserve fuel.",
        unit: "km",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Thrust-to-Weight Ratio",
        description: "Ratio of maximum engine thrust to aircraft weight, affecting acceleration and maneuverability.",
        unit: "ratio",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Radar Detection Range",
        description: "Maximum distance at which the aircraft's radar can detect a target with specified radar cross-section.",
        unit: "km",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Maximum G-Force Rating",
        description: "Maximum sustained gravitational force the airframe can withstand during high-performance maneuvers.",
        unit: "G",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Weapon Payload Capacity",
        description: "Maximum weight of ordnance the aircraft can carry on external and internal storage points.",
        unit: "kg",
        valueType: "number",
        childParameterIds: []
      }
    ]
  },
  "Electric Vehicle": {
    Mission: [
      {
        title: "Urban Mobility Solution",
        description: "Provide efficient, zero-emission transportation optimized for high-density urban environments.",
        childMissionIds: []
      },
      {
        title: "Long-Range Highway Travel",
        description: "Enable extended travel between cities with minimal charging stops and optimized energy consumption.",
        childMissionIds: []
      },
      {
        title: "Sustainable Fleet Operations",
        description: "Develop vehicle systems that reduce total cost of ownership for commercial fleet operators while minimizing environmental impact.",
        childMissionIds: []
      },
      {
        title: "Grid Integration Services",
        description: "Utilize vehicle battery capacity to provide stability services to electrical grids through bidirectional charging capabilities.",
        childMissionIds: []
      },
      {
        title: "Autonomous Transportation Network",
        description: "Create vehicle platforms optimized for self-driving operation in shared mobility applications.",
        childMissionIds: []
      }
    ],
    Parameter: [
      {
        title: "Battery Energy Capacity",
        description: "Total energy storage available in the vehicle's battery pack.",
        unit: "kWh",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Maximum Driving Range",
        description: "Distance the vehicle can travel on a full charge under standardized conditions.",
        unit: "km",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "DC Fast Charging Rate",
        description: "Maximum power at which the battery can accept charge from DC fast charging stations.",
        unit: "kW",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Energy Consumption Efficiency",
        description: "Energy used per unit distance during standardized driving cycle.",
        unit: "Wh/km",
        valueType: "number",
        childParameterIds: []
      },
      {
        title: "Battery Thermal Management Range",
        description: "Temperature range within which the battery management system can maintain optimal cell temperature.",
        unit: "°C",
        valueType: "range",
        childParameterIds: []
      }
    ]
  }
};

// POST /api/ai-generator/preview
// Body: { domain: 'Mission', count: 5, depth: 2, programType: 'Missile System' }
router.post('/preview', async (req, res) => {
  const { domain, count = 5, depth = 1, programType = '' } = req.body;
  
  if (!domain || !domainTemplates[domain]) {
    return res.status(400).json({ error: 'Invalid domain specified' });
  }
  
  try {
    console.log(`Generating preview for ${count} ${domain} objects with program type: ${programType}`);
    
    // Verify database connection first
    try {
      const session = driver.session();
      await session.run('RETURN 1 as test');
      await session.close();
    } catch (dbError) {
      console.error('Database connection error:', dbError);
      return res.status(500).json({ 
        error: 'Database connection error',
        details: 'Unable to connect to Neo4j database. Please ensure Neo4j is running and accessible.',
        dbError: dbError.message
      });
    }
    
    // Generate preview items without saving to database
    const previewItems = generatePreviewItems(domain, count, depth, programType);
    
    res.json({
      success: true,
      message: `Generated preview of ${previewItems.length} ${domain} items`,
      previewItems: previewItems
    });
    
  } catch (error) {
    console.error(`Error generating ${domain} preview:`, error);
    res.status(500).json({ 
      error: `Failed to generate ${domain} preview`, 
      details: error.message 
    });
  }
});

// POST /api/ai-generator/approve
// Body: { domain: 'Mission', items: [...], connectToNext: true, programType: 'Missile System' }
router.post('/approve', async (req, res) => {
  const { domain, items = [], connectToNext = true, programType = '' } = req.body;
  
  if (!domain || !domainTemplates[domain]) {
    return res.status(400).json({ error: 'Invalid domain specified' });
  }
  
  if (!Array.isArray(items) || items.length === 0) {
    return res.status(400).json({ error: 'No items provided to approve' });
  }
  
  // Check database connectivity
  let session;
  try {
    session = driver.session();
    await session.run('RETURN 1 as test');
  } catch (dbError) {
    console.error('Database connection error:', dbError);
    return res.status(500).json({ 
      error: 'Database connection error',
      details: 'Unable to connect to Neo4j database. Please ensure Neo4j is running and accessible.',
      dbError: dbError.message
    });
  }
  
  try {
    console.log(`Approving ${items.length} ${domain} items with program type: ${programType}`);
    
    // Save the approved items to the database
    const result = await saveApprovedItems(session, domain, items, connectToNext);
    
    res.json({
      success: true,
      message: `Successfully added ${result.itemsCreated} ${domain} items with ${result.connectionsCreated} relationships`,
      itemsCreated: result.itemsCreated,
      connectionsCreated: result.connectionsCreated,
      programType: programType
    });
    
  } catch (error) {
    console.error(`Error approving ${domain} items:`, error);
    res.status(500).json({ 
      error: `Failed to approve ${domain} items`, 
      details: error.message 
    });
  } finally {
    if (session) {
      await session.close();
    }
  }
});

// Helper function to generate preview items without saving to database
function generatePreviewItems(domain, count, depth, programType) {
  // Choose templates based on program type if available
  let templates = domainTemplates[domain];
  
  // If program type is specified and we have templates for it, use those
  if (programType && 
      programSpecificTemplates[programType] && 
      programSpecificTemplates[programType][domain]) {
    templates = programSpecificTemplates[programType][domain];
    console.log(`Using program-specific templates for ${programType} - ${domain}`);
  } else {
    console.log(`Using generic templates for ${domain}, no specific templates for ${programType}`);
  }
  
  const previewItems = [];
  
  // Create a single top-level parent
  const templateIndex = Math.floor(Math.random() * templates.length);
  const template = templates[templateIndex];
  
  // Generate a unique ID for the parent
  const parentId = `PREVIEW-${domain.substring(0, 3).toUpperCase()}-ROOT`;
  
  // Create the parent item with base properties
  const parentItem = {
    id: parentId,
    title: `${programType} ${template.title}`, // Include program type in top-level title
    description: template.description,
    programType: programType,
    isParent: true,
    level: 0
  };
  
  // Add domain-specific properties
  if (domain === 'Parameter') {
    parentItem.unit = template.unit;
    parentItem.valueType = template.valueType;
  } else if (domain === 'Functions') {
    parentItem.functionType = template.functionType;
  }
  
  previewItems.push(parentItem);
  
  // Generate children items based on the count
  const parentChildMap = {}; // Track children for each parent

  for (let i = 0; i < count; i++) {
    // Select a random template for the child
    const childTemplateIndex = Math.floor(Math.random() * templates.length);
    const childTemplate = templates[childTemplateIndex];
    
    // Generate a unique ID for the child
    const childId = `PREVIEW-${domain.substring(0, 3).toUpperCase()}-CHILD-${(i + 1).toString().padStart(3, '0')}`;
    
    // Create the child item
    const childItem = {
      id: childId,
      title: `${childTemplate.title} ${i + 1}`,
      description: childTemplate.description,
      programType: programType,
      parentId: parentId, // Reference to parent
      level: 1
    };
    
    // Add domain-specific properties
    if (domain === 'Parameter') {
      childItem.unit = childTemplate.unit;
      childItem.valueType = childTemplate.valueType;
    } else if (domain === 'Functions') {
      childItem.functionType = childTemplate.functionType;
    }
    
    previewItems.push(childItem);
    
    // Add child ID to parent map
    if (!parentChildMap[parentId]) parentChildMap[parentId] = [];
    parentChildMap[parentId].push(childId);

    // Generate grandchildren if depth > 1
    if (depth > 1) {
      const grandchildrenPerChild = Math.max(2, Math.floor(Math.random() * 4)); 
      for (let j = 0; j < grandchildrenPerChild; j++) {
        // Select a random template for the grandchild
        const grandchildTemplateIndex = Math.floor(Math.random() * templates.length);
        const grandchildTemplate = templates[grandchildTemplateIndex];
        
        // Generate a unique ID for the grandchild
        const grandchildId = `PREVIEW-${domain.substring(0, 3).toUpperCase()}-GRANDCHILD-${i}-${j}`;
        
        // Create the grandchild item
        const grandchildItem = {
          id: grandchildId,
          title: `${grandchildTemplate.title} ${i}.${j + 1}`,
          description: grandchildTemplate.description,
          programType: programType,
          parentId: childId, // Reference to parent child
          level: 2
        };
        
        // Add domain-specific properties
        if (domain === 'Parameter') {
          grandchildItem.unit = grandchildTemplate.unit;
          grandchildItem.valueType = grandchildTemplate.valueType;
        } else if (domain === 'Functions') {
          grandchildItem.functionType = grandchildTemplate.functionType;
        }
        
        previewItems.push(grandchildItem);

        // Add grandchild ID to parent (childItem) map
        if (!parentChildMap[childId]) parentChildMap[childId] = [];
        parentChildMap[childId].push(grandchildId);
        
        // Generate great-grandchildren if depth > 2
        if (depth > 2) {
          const greatGrandchildrenPerGrandchild = 2; 
          for (let k = 0; k < greatGrandchildrenPerGrandchild; k++) {
            // Select a random template for the great-grandchild
            const greatGrandchildTemplateIndex = Math.floor(Math.random() * templates.length);
            const greatGrandchildTemplate = templates[greatGrandchildTemplateIndex];
            
            // Generate a unique ID for the great-grandchild
            const greatGrandchildId = `PREVIEW-${domain.substring(0, 3).toUpperCase()}-GREATGRANDCHILD-${i}-${j}-${k}`;
            
            // Create the great-grandchild item
            const greatGrandchildItem = {
              id: greatGrandchildId,
              title: `${greatGrandchildTemplate.title} ${i}.${j}.${k + 1}`,
              description: greatGrandchildTemplate.description,
              programType: programType,
              parentId: grandchildId, // Reference to parent grandchild
              level: 3
            };
            
            // Add domain-specific properties
            if (domain === 'Parameter') {
              greatGrandchildItem.unit = greatGrandchildTemplate.unit;
              greatGrandchildItem.valueType = greatGrandchildTemplate.valueType;
            } else if (domain === 'Functions') {
              greatGrandchildItem.functionType = greatGrandchildTemplate.functionType;
            }
            
            previewItems.push(greatGrandchildItem);

            // Add great-grandchild ID to parent (grandchildItem) map
            if (!parentChildMap[grandchildId]) parentChildMap[grandchildId] = [];
            parentChildMap[grandchildId].push(greatGrandchildId);
          }
        }
      }
    }
  }
  
  // Now, add the child ID arrays to the items in previewItems
  const childIdKey = `child${domain.replace(/\s+/g, '')}Ids`;
  previewItems.forEach(item => {
    if (parentChildMap[item.id]) {
      item[childIdKey] = parentChildMap[item.id];
    } else {
      // Ensure the key exists even if empty for consistency
      item[childIdKey] = []; 
    }
  });

  return previewItems;
}

// Function to save approved items to the database
async function saveApprovedItems(session, domain, items, connectToNext) {
  let itemsCreated = 0;
  let connectionsCreated = 0;
  
  // Start a transaction
  const tx = session.beginTransaction();
  try {
    // First, create a map of preview IDs to new database IDs
    const idMap = {};
    
    // Process each approved item
    for (const item of items) {
      // Generate a new unique ID
      const itemId = generateId(domain, itemsCreated + 1);
      
      // Map the preview ID to the new database ID
      idMap[item.id] = itemId;
      
      // Create the final item for the database, preserving child array
      const dbItem = { ...item }; // Start by copying the approved item
      dbItem.id = itemId; // Set the new database ID
      dbItem.createdAt = new Date().toISOString();

      // Remove preview-specific properties *but keep child array*
      delete dbItem.parentId;
      delete dbItem.isParent;
      delete dbItem.level;
      
      // Ensure child array exists if not provided (e.g., for leaf nodes)
      const childIdKeyForSave = `child${domain.replace(/\s+/g, '')}Ids`;
      if (!dbItem.hasOwnProperty(childIdKeyForSave)) {
          dbItem[childIdKeyForSave] = [];
      } else {
        // Ensure it's an array (if it exists)
        dbItem[childIdKeyForSave] = Array.isArray(dbItem[childIdKeyForSave]) ? dbItem[childIdKeyForSave] : [];
      }

      // Create the node in Neo4j
      await tx.run(
        `CREATE (n:${domain} $item) RETURN n`,
        { item: dbItem }
      );
      
      itemsCreated++;
    }
    
    // Optional: Connect to next domain if specified
    // (Add logic here if needed based on connectToNext flag)

    await tx.commit();
    console.log(`Successfully created ${itemsCreated} items for domain ${domain}`);
    // Adjusted success message to reflect only item creation
    return { itemsCreated, connectionsCreated: 0 }; // connectionsCreated is now 0

  } catch (error) {
    console.error(`Error saving items for domain ${domain}:`, error);
    await tx.rollback();
    throw error; // Re-throw the error to be caught by the route handler
  }
}

// POST /api/ai-generator/generate
// Body: { domain: 'Mission', count: 5, depth: 2, connectToNext: true, programType: 'Missile System' }
router.post('/generate', async (req, res) => {
  const { domain, count = 5, depth = 1, connectToNext = true, programType = '' } = req.body;
  
  if (!domain || !domainTemplates[domain]) {
    return res.status(400).json({ error: 'Invalid domain specified' });
  }
  
  // Check database connectivity
  const session = driver.session();
  try {
    console.log(`Generating ${count} ${domain} objects with depth ${depth} for program type: ${programType}`);
    
    const result = await generateDomainItems(session, domain, count, depth, programType);
    
    // If connectToNext is true and this isn't the last domain, create connections
    if (connectToNext) {
      // Connect to items in the next domain if needed
      // Implementation in a future update
    }
    
    res.json({
      success: true,
      message: `Successfully generated ${result.itemsCreated} ${domain} items with ${result.connectionsCreated} relationships`,
      itemsCreated: result.itemsCreated,
      connectionsCreated: result.connectionsCreated,
      programType: programType
    });
    
  } catch (error) {
    console.error(`Error generating ${domain} items:`, error);
    res.status(500).json({ 
      error: `Failed to generate ${domain} items`, 
      details: error.message 
    });
  } finally {
    await session.close();
  }
});

// Function to generate items for a specific domain with hierarchical structure
async function generateDomainItems(session, domain, count, depth, programType) {
  // Choose templates based on program type if available
  let templates = domainTemplates[domain];
  
  // If program type is specified and we have templates for it, use those
  if (programType && 
      programSpecificTemplates[programType] && 
      programSpecificTemplates[programType][domain]) {
    templates = programSpecificTemplates[programType][domain];
    console.log(`Using program-specific templates for ${programType} - ${domain}`);
  } else {
    console.log(`Using generic templates for ${domain}, no specific templates for ${programType}`);
  }
  
  const items = [];
  let itemsCreated = 0;
  let connectionsCreated = 0;
  
  // Start a transaction
  const tx = session.beginTransaction();
  try {
    // Create top-level items
    for (let i = 0; i < count; i++) {
      // Select a random template
      const templateIndex = Math.floor(Math.random() * templates.length);
      const template = templates[templateIndex];
      
      // Generate a unique ID
      const itemId = generateId(domain, i + 1);
      
      // Create the item with base properties
      const item = {
        id: itemId,
        title: `${template.title} ${i + 1}`,
        description: template.description,
        createdAt: new Date().toISOString(),
        programType: programType // Store the program type with the item
      };
      
      // Add domain-specific properties
      if (domain === 'Parameter') {
        item.unit = template.unit;
        item.valueType = template.valueType;
      } else if (domain === 'Functions') {
        item.functionType = template.functionType;
      }
      
      // Initialize childIds array property based on domain
      const childIdsProperty = `child${domain}Ids`;
      item[childIdsProperty] = [];
      
      // Create the node in Neo4j
      const result = await tx.run(
        `CREATE (n:${domain} $item) RETURN n`,
        { item }
      );
      
      itemsCreated++;
      items.push(item);
      
      // Generate child items if depth > 1
      if (depth > 1) {
        const childrenPerItem = Math.max(2, Math.floor(Math.random() * 4)); // 2-3 children per item
        const childIds = [];
        
        for (let j = 0; j < childrenPerItem; j++) {
          // Select a random template for the child
          const childTemplateIndex = Math.floor(Math.random() * templates.length);
          const childTemplate = templates[childTemplateIndex];
          
          // Generate a unique ID for the child
          const childId = `${itemId}-CHILD-${(j + 1).toString().padStart(3, '0')}`;
          childIds.push(childId);
          
          // Create the child item with base properties
          const childItem = {
            id: childId,
            title: `${childTemplate.title} ${i + 1}.${j + 1}`,
            description: childTemplate.description,
            createdAt: new Date().toISOString(),
            programType: programType
          };
          
          // Add domain-specific properties
          if (domain === 'Parameter') {
            childItem.unit = childTemplate.unit;
            childItem.valueType = childTemplate.valueType;
          } else if (domain === 'Functions') {
            childItem.functionType = childTemplate.functionType;
          }
          
          // Initialize childIds array property for child
          childItem[childIdsProperty] = [];
          
          // Create the child node in Neo4j
          await tx.run(
            `CREATE (n:${domain} $item) RETURN n`,
            { item: childItem }
          );
          
          // Create relationship between parent and child
          await tx.run(
            `
            MATCH (parent:${domain} {id: $parentId})
            MATCH (child:${domain} {id: $childId})
            CREATE (parent)-[:HAS_CHILD]->(child)
            `,
            { parentId: itemId, childId }
          );
          
          itemsCreated++;
          connectionsCreated++;
          
          // Generate grandchildren if depth > 2
          if (depth > 2) {
            const grandchildrenPerChild = Math.max(2, Math.floor(Math.random() * 3)); // 2-3 grandchildren
            const grandchildIds = [];
            
            for (let k = 0; k < grandchildrenPerChild; k++) {
              // Select a random template for the grandchild
              const grandchildTemplateIndex = Math.floor(Math.random() * templates.length);
              const grandchildTemplate = templates[grandchildTemplateIndex];
              
              // Generate a unique ID for the grandchild
              const grandchildId = `${childId}-CHILD-${(k + 1).toString().padStart(3, '0')}`;
              grandchildIds.push(grandchildId);
              
              // Create the grandchild item
              const grandchildItem = {
                id: grandchildId,
                title: `${grandchildTemplate.title} ${i + 1}.${j + 1}.${k + 1}`,
                description: grandchildTemplate.description,
                createdAt: new Date().toISOString(),
                programType: programType
              };
              
              // Add domain-specific properties
              if (domain === 'Parameter') {
                grandchildItem.unit = grandchildTemplate.unit;
                grandchildItem.valueType = grandchildTemplate.valueType;
              } else if (domain === 'Functions') {
                grandchildItem.functionType = grandchildTemplate.functionType;
              }
              
              // Create the grandchild node in Neo4j
              await tx.run(
                `CREATE (n:${domain} $item) RETURN n`,
                { item: grandchildItem }
              );
              
              // Create relationship between child and grandchild
              await tx.run(
                `
                MATCH (parent:${domain} {id: $parentId})
                MATCH (child:${domain} {id: $childId})
                CREATE (parent)-[:HAS_CHILD]->(child)
                `,
                { parentId: childId, childId: grandchildId }
              );
              
              itemsCreated++;
              connectionsCreated++;
            }
            
            // Update the child item with grandchildIds
            await tx.run(
              `
              MATCH (child:${domain} {id: $childId})
              SET child.${childIdsProperty} = $grandchildIds
              `,
              { childId, grandchildIds }
            );
          }
        }
        
        // Update the parent item with childIds
        await tx.run(
          `
          MATCH (parent:${domain} {id: $parentId})
          SET parent.${childIdsProperty} = $childIds
          `,
          { parentId: itemId, childIds }
        );
      }
    }
    
    // Commit the transaction
    await tx.commit();
    
    return { itemsCreated, connectionsCreated };
  } catch (error) {
    // Rollback the transaction in case of error
    await tx.rollback();
    throw error;
  }
}

module.exports = router;